(define (root2 x)
  (define (avg a b)
    (/ (+ a b) 2))
  (define (improve2 y x)
    (avg (/ x y) y))
  (define (good? y z)
    (= y z))
  (define (iter2 y x z)
    (if (good? y z)
      y (iter2 (improve2 y x) x y)))
  (iter2 1.0 x 0))

(define (root3 x)
  (define (square f) (* f f))
  (define (improve3 y x)
    (/ (+ (/ x (square y)) (* 2 y)) 3))
  (define (good? y z)
    (< (root2 (square (- y z))) 0.000000001))
  (define (iter3 y x z)
    (if (good? y z)
      y (iter3 (improve3 y x) x y)))
  (iter3 1.0 x 0))
